# ==================================================
# Application
# ==================================================

spring.application.name=identity-service
server.port=8080


# ==================================================
# PostgreSQL / Supabase
# ==================================================

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:postgres}?sslmode=${DB_SSL_MODE:require}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ==================================================
# JPA / Hibernate
# ==================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:identity}

spring.jpa.open-in-view=false

# Useful while developing. Can disable later.
spring.jpa.show-sql=false


# ==================================================
# Flyway
# ==================================================

spring.flyway.enabled=true
spring.flyway.schemas=${DB_SCHEMA:identity}
spring.flyway.default-schema=${DB_SCHEMA:identity}
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration


# ==================================================
# JWT
# ==================================================

weav.jwt.access-secret=${JWT_ACCESS_SECRET}
weav.jwt.refresh-secret=${JWT_REFRESH_SECRET}
weav.jwt.access-expires-in=${JWT_ACCESS_EXPIRES_IN:15m}
weav.jwt.refresh-expires-in=${JWT_REFRESH_EXPIRES_IN:7d}

# ==================================================
# HikariCP
# ==================================================
# Đang limit số lượng kết nối tối đa để tránh quá tải cơ sở dữ liệu là 3, sau này có thêm database thì sẽ tăng lên

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=300000