#!/usr/bin/env python3
"""Domain layer package for OCR service."""

from src.domain.errors import (
    AnimatedImageUnsupportedError,
    ArtifactNotFoundError,
    CorruptFileError,
    DocumentLimitExceededError,
    EncryptedPdfError,
    FileTooLargeError,
    ForbiddenError,
    InternalError,
    InvalidOptionsError,
    InvalidRequestError,
    ModelNotReadyError,
    OcrBusyError,
    OcrDomainError,
    OcrTimeoutError,
    OutputLimitExceededError,
    RateLimitedError,
    RequestTimeoutError,
    SourceFetchFailedError,
    SourceTimeoutError,
    SourceUnavailableError,
    SourceUrlNotAllowedError,
    TableExtractionFailedError,
    UnauthenticatedError,
    UnsupportedMediaTypeError,
    UploadTimeoutError,
)

__all__ = [
    "AnimatedImageUnsupportedError",
    "ArtifactNotFoundError",
    "CorruptFileError",
    "DocumentLimitExceededError",
    "EncryptedPdfError",
    "FileTooLargeError",
    "ForbiddenError",
    "InternalError",
    "InvalidOptionsError",
    "InvalidRequestError",
    "ModelNotReadyError",
    "OcrBusyError",
    "OcrDomainError",
    "OcrTimeoutError",
    "OutputLimitExceededError",
    "RateLimitedError",
    "RequestTimeoutError",
    "SourceFetchFailedError",
    "SourceTimeoutError",
    "SourceUnavailableError",
    "SourceUrlNotAllowedError",
    "TableExtractionFailedError",
    "UnauthenticatedError",
    "UnsupportedMediaTypeError",
    "UploadTimeoutError",
]
