import type { NodeCatalogItem } from '../../types/workflow.types';

export const NODE_CATALOG: NodeCatalogItem[] = [
  {
    type: 'trigger.manual',
    title: 'Manual Trigger',
    description: 'Run the workflow manually with JSON input.',
    category: 'trigger',
    iconName: 'Play',
    defaultConfig: { buttonLabel: 'Run Now' },
    inputs: [],
    outputs: [{ name: 'input', type: 'object' }],
  },
  {
    type: 'trigger.schedule',
    title: 'Schedule (Cron)',
    description: 'Run the workflow on a Spring six-field cron schedule.',
    category: 'trigger',
    iconName: 'Clock',
    defaultConfig: { cron: '0 0 9 * * *', timezone: 'Asia/Ho_Chi_Minh' },
    inputs: [],
    outputs: [{ name: 'scheduledAt', type: 'string' }],
  },
  {
    type: 'trigger.webhook',
    title: 'Webhook Trigger',
    description: 'Receive JSON input at a system-provisioned webhook endpoint.',
    category: 'trigger',
    iconName: 'Webhook',
    defaultConfig: { method: 'POST' },
    inputs: [],
    outputs: [{ name: 'input', type: 'object' }],
  },
  {
    type: 'trigger.telegram',
    title: 'Telegram Bot Event',
    description: 'Telegram trigger; Bot Service contract is not available yet.',
    category: 'trigger',
    iconName: 'Send',
    defaultConfig: {},
    inputs: [],
    outputs: [],
  },
  {
    type: 'http.request',
    title: 'HTTP Request',
    description: 'Send an outbound HTTP request using Workflow V1 controls.',
    category: 'action',
    iconName: 'Globe',
    defaultConfig: { method: 'GET', url: '', headers: {}, query: {}, body: '' },
    inputs: [{ name: 'input', type: 'any' }],
    outputs: [{ name: 'data', type: 'any' }, { name: 'status', type: 'number' }],
  },
  {
    type: 'email.send',
    title: 'Send Email (Gmail)',
    description: 'Send an email (text or HTML, cc/bcc, attachments) from an authorized Gmail connection.',
    category: 'action',
    iconName: 'Mail',
    defaultConfig: { to: '', subject: '', body: '' },
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'messageId', type: 'string' }, { name: 'status', type: 'string' }],
  },
  {
    type: 'google.sheets',
    title: 'Google Sheets',
    description: 'Read, write or look up spreadsheet rows using an authorized Workspace connection.',
    category: 'action',
    iconName: 'FileSpreadsheet',
    defaultConfig: {
      connectionId: '',
      operation: 'read',
      spreadsheetId: '',
      // No sheet name: Google uses the first tab, whatever its localized name ("Sheet1", "Trang tính1").
      range: 'A1:Z100',
    },
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'result', type: 'object' }],
  },
  {
    type: 'telegram.send_message',
    title: 'Telegram Send Message',
    description: "Send a message through the workspace's Telegram bot.",
    category: 'action',
    iconName: 'Send',
    defaultConfig: { chatId: '', text: '' },
    inputs: [{ name: 'text', type: 'string' }],
    outputs: [{ name: 'messageId', type: 'string' }],
  },
  {
    type: 'logic.condition',
    title: 'If / Condition',
    description: 'Compare values (one condition or several combined with AND/OR) and route through true or false.',
    category: 'logic',
    iconName: 'GitBranch',
    defaultConfig: { left: '', operator: 'eq', right: '' },
    inputs: [{ name: 'value', type: 'any' }],
    outputs: [],
    sourcePorts: [
      { id: 'true', label: 'True' },
      { id: 'false', label: 'False' },
    ],
  },
  {
    type: 'ai.extract',
    title: 'AI Structured Extract',
    description: 'Extract structured JSON from text with an output schema.',
    category: 'ai',
    iconName: 'Sparkles',
    defaultConfig: {},
    inputs: [{ name: 'text', type: 'string' }],
    outputs: [{ name: 'extractedJson', type: 'object' }],
  },
  {
    type: 'ai.classify',
    title: 'AI Text Classifier',
    description: 'Pick one of your categories for a text.',
    category: 'ai',
    iconName: 'Tags',
    defaultConfig: { categories: [] },
    inputs: [{ name: 'content', type: 'string' }],
    outputs: [{ name: 'category', type: 'string' }, { name: 'confidence', type: 'number' }],
  },
  {
    type: 'ai.summarize',
    title: 'AI Summarizer',
    description: 'Summarize text within a character limit.',
    category: 'ai',
    iconName: 'FileText',
    defaultConfig: { maxLength: 200 },
    inputs: [{ name: 'inputText', type: 'string' }],
    outputs: [{ name: 'summary', type: 'string' }],
  },
  {
    type: 'trigger.gmail',
    title: 'New Gmail email',
    description: 'Start the workflow when a Gmail search finds a new email.',
    category: 'trigger',
    iconName: 'Inbox',
    defaultConfig: { pollIntervalMinutes: 5 },
    inputs: [],
    outputs: [{ name: 'input', type: 'object' }],
  },
  {
    type: 'google.drive',
    title: 'Google Drive',
    description: 'Upload a file to or list files in Google Drive.',
    category: 'action',
    iconName: 'HardDrive',
    defaultConfig: { operation: 'upload' },
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'result', type: 'object' }],
  },
  {
    type: 'google.calendar',
    title: 'Google Calendar',
    description: 'Create or list Google Calendar events.',
    category: 'action',
    iconName: 'CalendarDays',
    defaultConfig: { operation: 'create' },
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'result', type: 'object' }],
  },
  {
    type: 'logic.switch',
    title: 'Switch',
    description: 'Route to the branch whose case equals the value, else default.',
    category: 'logic',
    iconName: 'Split',
    defaultConfig: { value: '', cases: [] },
    inputs: [{ name: 'value', type: 'any' }],
    outputs: [],
    // The case ports come from config.cases (nodeSourcePorts); "default" always exists.
    sourcePorts: [{ id: 'default', label: 'Default' }],
  },
  {
    type: 'data.set',
    title: 'Set data',
    description: 'Build named values from literals and mappings for later steps.',
    category: 'logic',
    iconName: 'Braces',
    defaultConfig: { fields: {} },
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'fields', type: 'object' }],
  },
  {
    type: 'ai.generate',
    title: 'Generate text with AI',
    description: 'Write text from a prompt and optional instructions.',
    category: 'ai',
    iconName: 'WandSparkles',
    defaultConfig: { prompt: '' },
    inputs: [{ name: 'prompt', type: 'string' }],
    outputs: [{ name: 'text', type: 'string' }],
  },
  {
    type: 'ocr.extract',
    title: 'OCR Text Extract',
    description: 'Workflow OCR execution is unavailable until service and artifact prerequisites are verified.',
    category: 'ocr',
    iconName: 'Scan',
    defaultConfig: { language: 'vi+en', detectTables: true },
    inputs: [{ name: 'artifactId', type: 'string' }, { name: 'fileUrl', type: 'string' }],
    outputs: [
      { name: 'rawText', type: 'string' },
      { name: 'pages', type: 'number' },
      { name: 'blocks', type: 'array' },
      { name: 'tables', type: 'array' },
      { name: 'confidence', type: 'number' },
    ],
  },
];

/** Output ports of a step: logic.switch has one per case plus "default"; others use the catalog. */
export const nodeSourcePorts = (type: string, config: Record<string, unknown>): Array<{ id: string; label: string }> | undefined => {
  if (type === 'logic.switch') {
    const cases = Array.isArray(config.cases) ? config.cases.filter((item): item is string => typeof item === 'string' && item.trim() !== '' && item !== 'default') : [];
    return [...new Set(cases)].map((item) => ({ id: item, label: item })).concat({ id: 'default', label: 'Default' });
  }
  return NODE_CATALOG.find((item) => item.type === type)?.sourcePorts;
};
