import type { NodeCatalogItem } from '../../types/workflow.types';

export const NODE_CATALOG: NodeCatalogItem[] = [
  // TRIGGERS
  {
    type: 'trigger.manual',
    title: 'Manual Trigger',
    description: 'Trigger workflow manually via button click or API call',
    category: 'trigger',
    iconName: 'Play',
    defaultConfig: { buttonLabel: 'Run Now' },
    inputs: [],
    outputs: [{ name: 'payload', type: 'object' }],
  },
  {
    type: 'trigger.schedule',
    title: 'Schedule (Cron)',
    description: 'Trigger workflow periodically based on schedule',
    category: 'trigger',
    iconName: 'Clock',
    defaultConfig: { cron: '0 9 * * 1-5', timezone: 'Asia/Ho_Chi_Minh' },
    inputs: [],
    outputs: [{ name: 'scheduledTime', type: 'string' }],
  },
  {
    type: 'trigger.webhook',
    title: 'Webhook Trigger',
    description: 'Receive incoming JSON webhook from external apps',
    category: 'trigger',
    iconName: 'Webhook',
    defaultConfig: { method: 'POST', path: '/webhook/v1/trigger' },
    inputs: [],
    outputs: [{ name: 'body', type: 'object' }, { name: 'headers', type: 'object' }],
  },
  {
    type: 'trigger.telegram',
    title: 'Telegram Bot Event',
    description: 'Trigger on incoming Telegram Bot commands or messages',
    category: 'trigger',
    iconName: 'Send',
    defaultConfig: { command: '/start' },
    inputs: [],
    outputs: [{ name: 'chatId', type: 'string' }, { name: 'text', type: 'string' }],
  },

  // ACTIONS
  {
    type: 'email.send',
    title: 'Send Email (Gmail)',
    description: 'Send HTML/Text email to target recipients',
    category: 'action',
    iconName: 'Mail',
    defaultConfig: { to: 'user@example.com', subject: 'Workflow Notification', body: 'Workflow finished successfully.' },
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'messageId', type: 'string' }, { name: 'status', type: 'string' }],
  },
  {
    type: 'sheets.read',
    title: 'Read Google Sheets',
    description: 'Fetch rows from a specified Google Sheet spreadsheet',
    category: 'action',
    iconName: 'FileSpreadsheet',
    defaultConfig: { spreadsheetId: '', range: 'Sheet1!A1:Z100' },
    inputs: [{ name: 'triggerData', type: 'any' }],
    outputs: [{ name: 'rows', type: 'array' }],
  },
  {
    type: 'sheets.append',
    title: 'Append to Sheets',
    description: 'Append new data row to Google Sheets document',
    category: 'action',
    iconName: 'FileSpreadsheet',
    defaultConfig: { spreadsheetId: '', sheetName: 'Sheet1' },
    inputs: [{ name: 'rowData', type: 'object' }],
    outputs: [{ name: 'updatedRange', type: 'string' }],
  },
  {
    type: 'http.request',
    title: 'HTTP Request',
    description: 'Send custom REST API request (GET, POST, PUT, DELETE)',
    category: 'action',
    iconName: 'Globe',
    defaultConfig: { method: 'GET', url: 'https://api.example.com/data', headers: {} },
    inputs: [{ name: 'params', type: 'object' }],
    outputs: [{ name: 'response', type: 'object' }, { name: 'status', type: 'number' }],
  },
  {
    type: 'telegram.send_message',
    title: 'Telegram Send Message',
    description: 'Send message or alert to Telegram channel or user',
    category: 'action',
    iconName: 'Send',
    defaultConfig: { chatId: '', text: 'Automation message from WEAV.' },
    inputs: [{ name: 'textPayload', type: 'string' }],
    outputs: [{ name: 'sentMessageId', type: 'string' }],
  },

  // AI
  {
    type: 'ai.extract',
    title: 'AI Structured Extract',
    description: 'Extract clean JSON fields from unstructured text using AI',
    category: 'ai',
    iconName: 'Sparkles',
    defaultConfig: { schemaDescription: 'Extract name, amount, date' },
    inputs: [{ name: 'text', type: 'string' }],
    outputs: [{ name: 'extractedJson', type: 'object' }],
  },
  {
    type: 'ai.classify',
    title: 'AI Text Classifier',
    description: 'Categorize incoming customer text into defined tags',
    category: 'ai',
    iconName: 'Tags',
    defaultConfig: { categories: ['Urgent', 'Inquiry', 'Feedback', 'Spam'] },
    inputs: [{ name: 'content', type: 'string' }],
    outputs: [{ name: 'category', type: 'string' }, { name: 'confidence', type: 'number' }],
  },
  {
    type: 'ai.summarize',
    title: 'AI Summarizer',
    description: 'Summarize documents, emails, or chat logs into key bullet points',
    category: 'ai',
    iconName: 'FileText',
    defaultConfig: { maxLength: 200 },
    inputs: [{ name: 'inputText', type: 'string' }],
    outputs: [{ name: 'summary', type: 'string' }],
  },
  {
    type: 'agent.task',
    title: 'Agentic AI Task',
    description: 'Execute multi-step goal using autonomous AI agent tools',
    category: 'ai',
    iconName: 'Bot',
    defaultConfig: { goal: 'Analyze sales report and generate recommendation' },
    inputs: [{ name: 'context', type: 'any' }],
    outputs: [{ name: 'result', type: 'string' }, { name: 'actionLogs', type: 'array' }],
  },

  // OCR
  {
    type: 'ocr.extract',
    title: 'OCR Text Extract',
    description: 'Extract raw text and key fields from scanned PDFs / images',
    category: 'ocr',
    iconName: 'Scan',
    defaultConfig: { language: 'vi+en', detectTables: true },
    inputs: [{ name: 'fileUrl', type: 'string' }],
    outputs: [{ name: 'rawText', type: 'string' }, { name: 'pages', type: 'number' }, { name: 'confidence', type: 'number' }],
  },
];
