import type { NodeCatalogItem } from '../../types/workflow.types';

export const NODE_CATALOG: NodeCatalogItem[] = [
  {
    type: 'trigger.manual',
    title: 'Manual Trigger',
    description: 'Run the workflow manually with JSON input.',
    category: 'trigger',
    iconName: 'Play',
    defaultConfig: { buttonLabel: 'Run Now' },
    inputs: [],
    outputs: [{ name: 'input', type: 'object' }],
  },
  {
    type: 'trigger.schedule',
    title: 'Schedule (Cron)',
    description: 'Run the workflow on a Spring six-field cron schedule.',
    category: 'trigger',
    iconName: 'Clock',
    defaultConfig: { cron: '0 0 9 * * *', timezone: 'Asia/Ho_Chi_Minh' },
    inputs: [],
    outputs: [{ name: 'scheduledAt', type: 'string' }],
  },
  {
    type: 'trigger.webhook',
    title: 'Webhook Trigger',
    description: 'Receive JSON input at a system-provisioned webhook endpoint.',
    category: 'trigger',
    iconName: 'Webhook',
    defaultConfig: { method: 'POST' },
    inputs: [],
    outputs: [{ name: 'input', type: 'object' }],
  },
  {
    type: 'trigger.telegram',
    title: 'Telegram Bot Event',
    description: 'Telegram trigger; Bot Service contract is not available yet.',
    category: 'trigger',
    iconName: 'Send',
    defaultConfig: {},
    inputs: [],
    outputs: [],
  },
  {
    type: 'http.request',
    title: 'HTTP Request',
    description: 'Send an outbound HTTP request using Workflow V1 controls.',
    category: 'action',
    iconName: 'Globe',
    defaultConfig: { method: 'GET', url: '', headers: {}, query: {}, body: '' },
    inputs: [{ name: 'input', type: 'any' }],
    outputs: [{ name: 'data', type: 'any' }, { name: 'status', type: 'number' }],
  },
  {
    type: 'email.send',
    title: 'Send Email (Gmail)',
    description: 'Email sending is unavailable until an approved send-capable connection exists.',
    category: 'action',
    iconName: 'Mail',
    defaultConfig: { to: '', subject: '', body: '' },
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'messageId', type: 'string' }, { name: 'status', type: 'string' }],
  },
  {
    type: 'google.sheets',
    title: 'Google Sheets',
    description: 'Read or write spreadsheet data using an authorized Workspace connection.',
    category: 'action',
    iconName: 'FileSpreadsheet',
    defaultConfig: {
      connectionId: '',
      operation: 'read',
      spreadsheetId: '',
      range: 'Sheet1!A1:Z100',
      sheetName: 'Sheet1',
      rowDataVariable: '{{ trigger.input.email }}',
      valueVariable: '{{ trigger.input.email }}',
    },
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'result', type: 'object' }],
  },
  {
    type: 'telegram.send_message',
    title: 'Telegram Send Message',
    description: 'Telegram sending is unavailable until the Bot/provider contract is implemented.',
    category: 'action',
    iconName: 'Send',
    defaultConfig: { chatId: '', text: '' },
    inputs: [{ name: 'text', type: 'string' }],
    outputs: [{ name: 'messageId', type: 'string' }],
  },
  {
    type: 'logic.condition',
    title: 'If / Condition',
    description: 'Evaluate a declarative JSON predicate and route through true or false.',
    category: 'logic',
    iconName: 'GitBranch',
    defaultConfig: { left: '', operator: 'eq', right: '' },
    inputs: [{ name: 'value', type: 'any' }],
    outputs: [],
    sourcePorts: [
      { id: 'true', label: 'True' },
      { id: 'false', label: 'False' },
    ],
  },
  {
    type: 'ai.extract',
    title: 'AI Structured Extract',
    description: 'AI provider is unavailable until its request/response contract is implemented.',
    category: 'ai',
    iconName: 'Sparkles',
    defaultConfig: { schemaDescription: '' },
    inputs: [{ name: 'text', type: 'string' }],
    outputs: [{ name: 'extractedJson', type: 'object' }],
  },
  {
    type: 'ai.classify',
    title: 'AI Text Classifier',
    description: 'AI provider is unavailable until its request/response contract is implemented.',
    category: 'ai',
    iconName: 'Tags',
    defaultConfig: { categories: [] },
    inputs: [{ name: 'content', type: 'string' }],
    outputs: [{ name: 'category', type: 'string' }, { name: 'confidence', type: 'number' }],
  },
  {
    type: 'ai.summarize',
    title: 'AI Summarizer',
    description: 'AI provider is unavailable until its request/response contract is implemented.',
    category: 'ai',
    iconName: 'FileText',
    defaultConfig: { maxLength: 200 },
    inputs: [{ name: 'inputText', type: 'string' }],
    outputs: [{ name: 'summary', type: 'string' }],
  },
  {
    type: 'ocr.extract',
    title: 'OCR Text Extract',
    description: 'Workflow OCR execution is unavailable until service and artifact prerequisites are verified.',
    category: 'ocr',
    iconName: 'Scan',
    defaultConfig: { language: 'vi+en', detectTables: true },
    inputs: [{ name: 'artifactId', type: 'string' }, { name: 'fileUrl', type: 'string' }],
    outputs: [
      { name: 'rawText', type: 'string' },
      { name: 'pages', type: 'number' },
      { name: 'blocks', type: 'array' },
      { name: 'tables', type: 'array' },
      { name: 'confidence', type: 'number' },
    ],
  },
];
