FROM node:24-bookworm

RUN corepack enable \
    && corepack prepare pnpm@11.22.0 --activate

WORKDIR /workspace

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

COPY services/notification-service/package.json ./services/notification-service/package.json
COPY packages ./packages

RUN pnpm install \
    --filter ./services/notification-service... \
    --frozen-lockfile

COPY services/notification-service ./services/notification-service

WORKDIR /workspace/services/notification-service

CMD ["pnpm", "start:dev"]