import type { AIRepository, AiGenerationResult } from '../../domain/ai/ai.types';

const delay = (ms = 500) => new Promise((resolve) => setTimeout(resolve, ms));

export class MockAiRepository implements AIRepository {
  async generateWorkflow(prompt: string): Promise<AiGenerationResult> {
    await delay(700);

    const generatedWfId = 'wf-ai-' + Date.now().toString(36);

    return {
      prompt,
      reasoning: `Analyzed user intent: "${prompt}". Identified 3 core automation stages: (1) Inbound Webhook trigger, (2) AI LLM data extraction & classification, and (3) Action delivery to Google Sheets / Telegram.`,
      workflowPreview: {
        id: generatedWfId,
        name: `AI Generated: ${prompt.slice(0, 32)}...`,
        description: `Automated DAG generated by WEAV AI Copilot from prompt: "${prompt}"`,
        status: 'DRAFT',
        version: 1,
        triggerType: 'trigger.webhook',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        ownerName: 'Nguyễn Anh Xuân Trường',
        workspaceId: 'ws-main',
        nodes: [
          { id: 'node-1', type: 'trigger.webhook', name: 'Inbound Webhook Trigger', config: { path: '/api/v1/ai-incoming' }, position: { x: 100, y: 100 } },
          { id: 'node-2', type: 'ai.extract', name: 'AI LLM Entity Extractor', config: { model: 'gpt-4o', fields: ['name', 'amount', 'summary'] }, position: { x: 450, y: 100 } },
          { id: 'node-3', type: 'sheets.append', name: 'Append to Google Sheets', config: { spreadsheetId: 'sheets-ai-01' }, position: { x: 800, y: 100 } },
        ],
        edges: [
          { id: 'e1-2', source: 'node-1', target: 'node-2' },
          { id: 'e2-3', source: 'node-2', target: 'node-3' },
        ],
      },
      validation: {
        valid: true,
        warnings: [
          'Google Sheets connection token required before publishing.',
          'Review AI field extraction mapping on Web Builder before running.',
        ],
      },
    };
  }
}
