FROM eclipse-temurin:25-jdk

WORKDIR /app

# Maven Wrapper cần dùng trong container
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./

RUN chmod +x mvnw

COPY src/ src/

CMD ["./mvnw", "spring-boot:run"]